### ISSUE TITLE
redux sagas unnecessary?

### ISSUE THREAD

**Issue by headwinds** [srghma/functional-nextjs-typescript-apollo-boilerplate#10]
I went through your awesome example and learned quite a lot.

I see that you actually decided not to use redux sagas though - did you do this because it's not necessary once you have Apollo setup?

This [Apollo article](https://dev-blog.apollodata.com/apollo-client-graphql-with-react-and-redux-49b35d0f2641) seems to confirm that redux-sagas may not be needed but if we wanted to talk to a API that wasn't using GraphQL wouldn't one still need to use a thunk or a saga to make that call?

**Comment by BjornMelgaard** [comment]
@headwinds loool)
sorry for late response, didn't received email about your comments

I have slightly abandoned this project lately

Sagas ... I think something like this is necessary (how I'll make auth module without them?), but I want to use redux-logic (application structure I saw when learned ngrx, [awesome article from creator](https://medium.com/@jeffbski/where-do-i-put-my-business-logic-in-a-react-redux-application-9253ef91ce1))

Also I want to try https://github.com/nozzle/react-static, [because next.js stopped in development](https://github.com/zeit/next.js/issues/2391)

Also seems like relay is better, because it doesn't make me do [low level error-prone things](https://github.com/BjornMelgaard/functional-nextjs-typescript-apollo-boilerplate/blob/master/app/containers/PostList/apollo.ts#L37)

Also containers structure will be like
```
\presentations
   \default.tsx
   \error.tsx
   \no-data.tsx
\feature.ts - joins presentations with recompose (branches, withState) 
\apollo/relay/dunno.ts
\index.ts - wraps feature.ts in apollo
```
